version: '3.4'

services:
  seekq.apigateway.bff.mobile:
    image: ${DOCKER_REGISTRY-}seekqapigatewaybffmobile
    ports:
      - "32700:80"
    build:
      context: .
      dockerfile: SeekQ.ApiGateway.BFF.Mobile/Dockerfile
    depends_on:
      - seekqmssql

  #ports: host:container
  seekqmssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: seekq.mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"

networks:
  default:
    external:
      name: SEEKQ_NETWORK


